name: Bump version
on:
  push:
    branches:
      - BOS-6833-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.0.7
          RELEASE_BRANCHES: BOS-6833-pipeline

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: make install

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist

      - name: Get project version
        id: get-version
        run: |
          echo '::echo::on'
          set +e
          echo ::set-output name=version::$(make version)
