name: Bump version
on:
  push:
    branches:
      - BOS-6833-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.0.7
          RELEASE_BRANCHES: BOS-6833-pipeline

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: make install

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist
        
      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     user: __token__
      #     password: pypi-AgEIcHlwaS5vcmcCJGY3ZWY2OGM1LTlhYzAtNGJiZS04Yjg2LTFkMGJlN2VhZjc4OQACP3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJva3RhZ29uLXB5dGhvbiJdfSwgInZlcnNpb24iOiAxfQAABiBim9A1kjA-1Fdlw-46u_9KMGuYWIvt88YQKBX97MpSSw
      #     repository_url: https://test.pypi.org/legacy/
      
      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: ${{ steps.tag.outputs.new_tag }}
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          files: |
            LICENSE.txt
            dist/*
  
      - name: Get project version
        id: get-version
        run: |
          echo '::echo::on'
          set +e
          echo ::set-output name=version::$(make version)
