name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: make install-deps
        
      - name: Black
        run: make black-check

      - name: Isort
        run: make isort-check

      - name: pylint
        run: make pytlint
