name: Pre-release

on:
  workflow_run:
    workflows: 
      - Tests
    types:
      - completed


jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install poetry
        run:  |
          pip install autopub
          pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
        
      - name: Check if RELEASE.md file exists
        id: check_release
        run: make check-release
      
      - name: Publish pre-release version
        if: steps.check_release.outputs.release == ''
        id: release
        env:
          OKTAGON_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make pre-release
